### ISSUE TITLE
Set up trouble

### ISSUE THREAD

**Issue by jonom** [webtorque7/inpage-modules#12]
Saw this module referenced on your SS blog post and was intrigued so gave it a shot. Installed via composer (defaulted to dev-master) and have had a bit of trouble getting things working. The docs seem a bit out of date and incomplete for first time set up? I tried filling in some gaps here and there but kept getting errors and problems. Some issues:

* Default 'ContentModules' many_many relationship appears to be expected/required by module, but is not defined in the `ContentModule_PageExtension` extension. Results in SQL error when loading preview in Visual Editor interface and inability to add any content blocks.
* Docs suggest you can opt in to add `ContentModule_PageExtension` to only certain page types, but the module's config.yml actually adds it to the base Page class automatically.
* Visual Editor only option for editing blocks? This is a cool feature but crashed on me with `
Fatal error: Call to a member function appendChild() on null in [...]/inpage-modules/code/model/ContentModule.php on line 1188` once I created my first content block. Would be good to have option of a basic editing tab within regular page editing interface.

Looks like a really promising module but would be great to make the first-time installation a clearer and smoother experience for developers so they're more likely to hang on through setup and adopt it.

**Comment by riddler7** [comment]
Yeah, the docs might've lagged a bit behind. Original design was for a single content area, hence applying the extension to Page.

Now when using I don't use this and instead setup the relationships myself on the page class. You can add a ContentModuleField in getCMSFields to add an editor on the main form (add it to it's own tab). This uses accordions to edit modules. 

The visual editor isn't available by default, it's a new feature and haven't decided how to expose it yet, on projects so far I've created a button on the main edit form linking to the visual editor to edit the page. 

Also, a gotcha for the modules is the template should have a single element at the root level (like react) as it uses dom document to insert some markup in the template when editing.

Fire any other questions through and I'll answer them as I can. Could send an you example how I've got it setup.

**Comment by jonom** [comment]
Thanks for the reply. I tried ContentModuleField and ContentModuleRelationshipEditor but got more errors. If you don't mind posting a working example setup that would be great!

**Comment by riddler7** [comment]
ContentModuleRelationshipEditor is basically a GridField for modules, uses a dialog for managing relationships, there's a static function off this now which will create a gridfield if using the visual editor (a little bit messy but didn't have time for a clean up).

A lot of the base code could do with a cleanup as it's quite old, the main thing this offers over other solutions is the UI.

Waiting to see what happens with SS4 and modules before going too much further, it's possible I'll pull out the interface and apply it to whatever solution is chosen for SS4.

I'll post my setup later today.

**Comment by riddler7** [comment]
Posted some sample files of how I've got it setup https://gist.github.com/riddler7/53128828a57b96df4e97b9fe6178c946
